### ISSUE TITLE
Chinese Remainder Theorem

### ISSUE THREAD

**Issue by shobonvip** [ebi-fly13/icpc_library#13]
互いに素な2以上の整数 m1, m2 と 0≦r1<m1, 0≦r2<m2 を渡したときに 0≦r<m1×m2 で r≡r1 (mod m1), r≡r2 (mod m2) を渡してくれるやつ（中国剰余定理）

inv_mod（(ℤ/nℤ)^× における逆元）もほしい！

**Comment by noya2ruler** [comment]
CRTは[ACL](https://atcoder.github.io/ac-library/document_ja/math.html)にありますが、そうではなく、ですか？（pythonのことなら、自分は全然わからないのでお任せします！）

**Comment by shobonvip** [comment]
ACL と同じです！
ACL はすべて library に追加するのですか？

**Comment by noya2ruler** [comment]
ACL以外は自分たちでどんなインターフェースのライブラリを使うかを決めないといけないんですけど、ACLにあるものはそれをそのまま使おうという話になっていると思います（たぶん）。ドキュメントもACLは充実しているので、ACLにあるものは既に追加されていると思って良いはずです！

**Comment by shobonvip** [comment]
okです！
