### ISSUE TITLE
modint

### ISSUE THREAD

**Issue by ebi-fly13** [ebi-fly13/icpc_library#23]
これくらいならmod取る問題があったら書いてもいい気がしてきた
https://noshi91.hatenablog.com/entry/2019/03/31/174006

**Comment by ebi-fly13** [comment]
書いた。https://github.com/ebi-fly13/icpc_library/blob/main/utility/modint.hpp

constexprはなくても動く

**Comment by noya2ruler** [comment]
自分の持ってるライブラリには `operator+` とかには `friend` 指定がついていて、必要かどうか気になっています（たぶん、`int+modint` をしたいときとかに必要？）。

```cpp
friend modint operator+(const modint& lhs, const modint& rhs) {
    return modint(lhs) += rhs;
}

^ by noya2

v by ebi-fly13

constexpr modint operator+(const modint rhs) {
    return modint(*this) += rhs;
}
```

あと、単項演算子 `modint operator-() const { return modint() - *this; }` は結構使う気がします。

**Comment by ebi-fly13** [comment]
直しました
