### ISSUE TITLE
Pow of Sparse FPS

### ISSUE THREAD

**Issue by shobonvip** [ebi-fly13/icpc_library#29]
$K$ 項しかない形式的冪級数 $f$ が与えられたとき,
その $f^M$ の $N$ 次までを $O(NK + \log P)$ で求める関数.

modint と階乗前計算を要求すると高速.
実装が軽い（20行くらいで終わる）

ぼくは vector<pair<int,mint>> で疎FPSを持つ勢力の一員です　紛争を開始？

**Comment by noya2ruler** [comment]
ICPC Asia を見据えるならどうせFPSは整備することになるだろうし、

- `FormalPowerSeries<mint>` 用
- `vector<mint>` 用

のどちらかがあれば十分だと思っています。まぁ、本質部分はFPSを何で持っても変わらないと思うので、今すぐ用意するだけなら `vector<pair<int,mint>>` で持ってもいいかも？

**Comment by ebi-fly13** [comment]
宗教戦争、開始……
https://ebi-fly13.github.io/Library/fps/fps_sparse.hpp
